USE [Limpiezas__RBD]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Clientes_2022](
	[DNI/CIF] [char](9) NOT NULL,
	[Telefono] [char](9) NULL,
	[Email] [varchar](20) NULL,
	[Calle] [varchar](50) NULL,
	[Numero] [int] NULL,
	[CP] [char](5) NULL,
 CONSTRAINT [Clientes2022_PK] PRIMARY KEY CLUSTERED 
(
	[DNI/CIF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



ALTER TABLE Clientes
SWITCH PARTITION 1 TO Clientes_2022 PARTITION 1;

USE [Limpiezas__RBD]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Empleados_2022](
	[DNI_E] [char](9) NOT NULL,
	[Nombre] [varchar](20) NULL,
	[Apellido] [varchar](30) NULL,
	[Telefono] [char](9) NULL,
	[Email] [varchar](50) NULL,
 CONSTRAINT [Empleados2022_PK] PRIMARY KEY CLUSTERED 
(
	[DNI_E] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



ALTER TABLE Empleados
SWITCH PARTITION 1 TO Empleados_2022 PARTITION 1;
